export enum NotificationTypes {
  SKILLS = 'SKILLS',
  CLIENT_PROJECT = 'CLIENT_PROJECT',
  EMPLOYMENT = 'EMPLOYMENT',
  CUSTOM = 'CUSTOM',
  PROJECT = 'PROJECT',
  TEAM = 'TEAM',
  CONNECTION = 'CONNECTION',
}
